sudo: false

language: java
jdk:
  - oraclejdk8

before_cache:
    - rm -rf $HOME/.m2/repository/com/pingconsole

before_install:
 - chmod +x gradlew
 
 
cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9