sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
services:
  - mysql
#install:
#- mvn clean install -DskipTests
#script:
#- mvn test
before_install:
 - chmod +x mvnw
 - mvn -N io.takari:maven:wrapper
 - mysql -e 'CREATE DATABASE IF NOT EXISTS neoPingDataBase;'
cache:
  directories:
  - $HOME/.m2