language: java
jdk:
- oraclejdk8
sudo: required
before_cache:
- rm -rf $HOME/.m2/repository/com/pingconsole
install:
- mvn claen install -DskipTests=true
cache:
  directories:
  - $HOME/.m2
  - $HOME/apache-maven-3.3.9